"""add disposal cache table

Revision ID: 88c17b041158
Revises: add_google_tokens
Create Date: 2026-04-11 16:53:17.441681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c17b041158'
down_revision: Union[str, Sequence[str], None] = 'add_google_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposal_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('material_type', sa.String(length=255), nullable=False),
    sa.Column('disposal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disposal_cache_expiry', 'disposal_cache', ['expires_at'], unique=False)
    op.create_index('idx_disposal_cache_lookup', 'disposal_cache', ['location', 'item_name', 'material_type'], unique=True)
    op.create_index(op.f('ix_disposal_cache_expires_at'), 'disposal_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_disposal_cache_item_name'), 'disposal_cache', ['item_name'], unique=False)
    op.create_index(op.f('ix_disposal_cache_location'), 'disposal_cache', ['location'], unique=False)
    op.create_index(op.f('ix_disposal_cache_material_type'), 'disposal_cache', ['material_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disposal_cache_material_type'), table_name='disposal_cache')
    op.drop_index(op.f('ix_disposal_cache_location'), table_name='disposal_cache')
    op.drop_index(op.f('ix_disposal_cache_item_name'), table_name='disposal_cache')
    op.drop_index(op.f('ix_disposal_cache_expires_at'), table_name='disposal_cache')
    op.drop_index('idx_disposal_cache_lookup', table_name='disposal_cache')
    op.drop_index('idx_disposal_cache_expiry', table_name='disposal_cache')
    op.drop_table('disposal_cache')
    # ### end Alembic commands ###
